// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Parrot

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_headline = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_parrot0_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 565
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 800
    lv_obj_set_x(ui_Image1, 12);
    lv_obj_set_y(ui_Image1, -8);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_headline = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_headline, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_headline, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_headline, 18);
    lv_obj_set_y(ui_headline, -168);
    lv_label_set_text(ui_headline, "i am nano");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image1 = NULL;
    ui_headline = NULL;

}
